name: use_case_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: any
  connectivity_plus: ^2.3.4
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_svg: ^1.1.5
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  kartal: ^2.3.2
  mobx: ^2.1.0
  pigeon: ^4.1.0
  uikit:
    path: module/uikit
  vexana: ^2.8.1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  json_serializable: ^6.0.0
  mobx_codegen: ^2.0.7+3
  very_good_analysis: ^3.1.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icon/
    - assets/icon/animal/
    - assets/svg/

flutter_gen:
  output: lib/product/generation/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_birds.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
