name: use_case_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_svg: ^2.0.4
  freezed: ^3.0.0-0.0.dev
  freezed_annotation: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  kartal: ^4.1.0
  mobx: ^2.1.0
  pigeon: ^22.7.2
  lottie: ^3.3.1
  async: ^2.9.0
  uikit:
    path: module/uikit
  vexana: ^5.0.3
  url_launcher: ^6.1.6
  image_picker: ^1.1.2
  app_settings: ^6.1.1
  permission_handler: ^12.0.0
  flutter_bloc: ^9.1.0
  provider: ^6.0.4

  chucker_flutter: ^1.4.3
  shake: ^3.0.0

  codegen:
    path: module/codegen

dev_dependencies:
  build_runner: ^2.2.1
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.0.0
  mobx_codegen: ^2.0.7+3
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  win32: ^5.5.4


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icon/
    - assets/svg/
    - assets/json/10k.json

flutter_gen:
  output: lib/product/generation/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_birds.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
