// Autogenerated from Pigeon (v4.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, Results) {
  ResultsSuccess = 0,
  ResultsFail = 1,
};

@class Value;
@class ResultModel;

@interface Value : NSObject
+ (instancetype)makeWithNumber:(nullable NSNumber *)number;
@property(nonatomic, strong, nullable) NSNumber * number;
@end

@interface ResultModel : NSObject
+ (instancetype)makeWithResult:(Results)result
    token:(nullable NSString *)token;
@property(nonatomic, assign) Results result;
@property(nonatomic, copy, nullable) NSString * token;
@end

///The codec used by Api2Host.
NSObject<FlutterMessageCodec> *Api2HostGetCodec(void);

@protocol Api2Host
- (void)calculateValue:(Value *)value completion:(void(^)(Value *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable ResultModel *)tokenParseId:(NSString *)id error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void Api2HostSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Api2Host> *_Nullable api);

NS_ASSUME_NONNULL_END
